services:
  db:
    container_name: db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          '/opt/mssql-tools18/bin/sqlcmd -S tcp:db,1433 -U sa -P "$DB_PASSWORD" -C -Q ''SELECT 1'' || exit 1',
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  app:
    container_name: veiling
    build:
      context: .
      dockerfile: Veiling.Server/Dockerfile
      args:
        BUILD_CONFIGURATION: Development
        CERT_PATH: ${CERT_PATH}
        CERT_PASSWORD: ${CERT_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${CERT_PASSWORD}
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/veiling.client.pfx
      DB_SERVER: tcp:db,1433
      DB_USERNAME: sa
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "7080:8081"
      - "32274:8080"
    volumes:
      - ${CERT_PATH}:/https:ro
    healthcheck:
      test:
        ["CMD-SHELL", "timeout 1 bash -c '</dev/tcp/0.0.0.0/8080' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 15s

volumes:
  sql_data:
