// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Veiling.Server;

#nullable disable

namespace Veiling.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251217202407_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Veiling.Server.Models.Bedrijf", b =>
                {
                    b.Property<int>("Bedrijfscode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Bedrijfscode"));

                    b.Property<string>("Bedrijfsnaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KVKnummer")
                        .HasColumnType("int");

                    b.HasKey("Bedrijfscode");

                    b.ToTable("Bedrijven");
                });

            modelBuilder.Entity("Veiling.Server.Models.Bod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Betaald")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Datumtijd")
                        .HasColumnType("datetime2");

                    b.Property<string>("GebruikerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("HoeveelheidContainers")
                        .HasColumnType("int");

                    b.Property<int?>("KavelId")
                        .HasColumnType("int");

                    b.Property<float>("Koopprijs")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("GebruikerId");

                    b.HasIndex("KavelId");

                    b.ToTable("Boden");
                });

            modelBuilder.Entity("Veiling.Server.Models.Gebruiker", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("BedrijfId")
                        .HasColumnType("int");

                    b.Property<bool>("Bedrijfsbeheerder")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("Geverifieerd")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("BedrijfId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Veiling.Server.Models.Kavel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AantalProductenPerContainer")
                        .HasColumnType("int");

                    b.Property<bool?>("Approved")
                        .HasColumnType("bit");

                    b.Property<string>("ArtikelKenmerken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Beschrijving")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Fustcode")
                        .HasColumnType("int");

                    b.Property<float>("GekochtPrijs")
                        .HasColumnType("real");

                    b.Property<int>("GekochteContainers")
                        .HasColumnType("int");

                    b.Property<string>("GeldPerTickCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("GewichtVanBloemen")
                        .HasColumnType("real");

                    b.Property<int>("HoeveelheidContainers")
                        .HasColumnType("int");

                    b.Property<int>("Karnummer")
                        .HasColumnType("int");

                    b.Property<string>("Kavelkleur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Keurcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("LengteVanBloemen")
                        .HasColumnType("real");

                    b.Property<int?>("LeverancierId")
                        .HasColumnType("int");

                    b.Property<float>("MaximumPrijs")
                        .HasColumnType("real");

                    b.Property<float>("MinimumPrijs")
                        .HasColumnType("real");

                    b.Property<int>("Minimumhoeveelheid")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NgsCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Reasoning")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rijnummer")
                        .HasColumnType("int");

                    b.Property<string>("StageOfMaturity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VeilingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeverancierId");

                    b.HasIndex("VeilingId");

                    b.ToTable("Kavels");
                });

            modelBuilder.Entity("Veiling.Server.Models.KavelVeiling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KavelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KavelId");

                    b.ToTable("KavelVeilingen");
                });

            modelBuilder.Entity("Veiling.Server.Models.Leverancier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BedrijfId")
                        .HasColumnType("int");

                    b.Property<string>("IndexOfReliabilityOfInformation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BedrijfId");

                    b.ToTable("Leveranciers");
                });

            modelBuilder.Entity("Veiling.Server.Models.Locatie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actief")
                        .HasColumnType("bit");

                    b.Property<int>("KlokId")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locaties");
                });

            modelBuilder.Entity("Veiling.Server.Models.Veiling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndTijd")
                        .HasColumnType("datetime2");

                    b.Property<float>("GeldPerTickCode")
                        .HasColumnType("real");

                    b.Property<float>("Klokduur")
                        .HasColumnType("real");

                    b.Property<int?>("LocatieId")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTijd")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VeilingmeesterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocatieId");

                    b.HasIndex("VeilingmeesterId");

                    b.ToTable("Veilingen");
                });

            modelBuilder.Entity("Veiling.Server.Models.Veilingmeester", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AantalVeilingenBeheerd")
                        .HasColumnType("int");

                    b.Property<string>("GebruikerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("GebruikerId");

                    b.ToTable("Veilingmeesters");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Veiling.Server.Models.Gebruiker", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Veiling.Server.Models.Gebruiker", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Veiling.Server.Models.Gebruiker", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Veiling.Server.Models.Gebruiker", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Veiling.Server.Models.Bod", b =>
                {
                    b.HasOne("Veiling.Server.Models.Gebruiker", "Gebruiker")
                        .WithMany("Boden")
                        .HasForeignKey("GebruikerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Veiling.Server.Models.Kavel", "Kavel")
                        .WithMany("Boden")
                        .HasForeignKey("KavelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Gebruiker");

                    b.Navigation("Kavel");
                });

            modelBuilder.Entity("Veiling.Server.Models.Gebruiker", b =>
                {
                    b.HasOne("Veiling.Server.Models.Bedrijf", "Bedrijf")
                        .WithMany("Gebruikers")
                        .HasForeignKey("BedrijfId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Bedrijf");
                });

            modelBuilder.Entity("Veiling.Server.Models.Kavel", b =>
                {
                    b.HasOne("Veiling.Server.Models.Leverancier", "Leverancier")
                        .WithMany("Kavels")
                        .HasForeignKey("LeverancierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Veiling.Server.Models.Veiling", "Veiling")
                        .WithMany("Kavels")
                        .HasForeignKey("VeilingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Leverancier");

                    b.Navigation("Veiling");
                });

            modelBuilder.Entity("Veiling.Server.Models.KavelVeiling", b =>
                {
                    b.HasOne("Veiling.Server.Models.Kavel", "Kavel")
                        .WithMany("KavelVeilingen")
                        .HasForeignKey("KavelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kavel");
                });

            modelBuilder.Entity("Veiling.Server.Models.Leverancier", b =>
                {
                    b.HasOne("Veiling.Server.Models.Bedrijf", "Bedrijf")
                        .WithMany()
                        .HasForeignKey("BedrijfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bedrijf");
                });

            modelBuilder.Entity("Veiling.Server.Models.Veiling", b =>
                {
                    b.HasOne("Veiling.Server.Models.Locatie", "Locatie")
                        .WithMany("Veilingen")
                        .HasForeignKey("LocatieId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Veiling.Server.Models.Veilingmeester", "Veilingmeester")
                        .WithMany("Veilingen")
                        .HasForeignKey("VeilingmeesterId");

                    b.Navigation("Locatie");

                    b.Navigation("Veilingmeester");
                });

            modelBuilder.Entity("Veiling.Server.Models.Veilingmeester", b =>
                {
                    b.HasOne("Veiling.Server.Models.Gebruiker", "Gebruiker")
                        .WithMany()
                        .HasForeignKey("GebruikerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gebruiker");
                });

            modelBuilder.Entity("Veiling.Server.Models.Bedrijf", b =>
                {
                    b.Navigation("Gebruikers");
                });

            modelBuilder.Entity("Veiling.Server.Models.Gebruiker", b =>
                {
                    b.Navigation("Boden");
                });

            modelBuilder.Entity("Veiling.Server.Models.Kavel", b =>
                {
                    b.Navigation("Boden");

                    b.Navigation("KavelVeilingen");
                });

            modelBuilder.Entity("Veiling.Server.Models.Leverancier", b =>
                {
                    b.Navigation("Kavels");
                });

            modelBuilder.Entity("Veiling.Server.Models.Locatie", b =>
                {
                    b.Navigation("Veilingen");
                });

            modelBuilder.Entity("Veiling.Server.Models.Veiling", b =>
                {
                    b.Navigation("Kavels");
                });

            modelBuilder.Entity("Veiling.Server.Models.Veilingmeester", b =>
                {
                    b.Navigation("Veilingen");
                });
#pragma warning restore 612, 618
        }
    }
}
