// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Veiling.Server;

#nullable disable

namespace Veiling.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251112094731_AddAfbeeldingUrlToKavel")]
    partial class AddAfbeeldingUrlToKavel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Veiling.Server.Models.Bedrijf", b =>
                {
                    b.Property<int>("Bedrijfscode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Bedrijfscode"));

                    b.Property<string>("Bedrijfsnaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KVKnummer")
                        .HasColumnType("int");

                    b.HasKey("Bedrijfscode");

                    b.ToTable("Bedrijven");
                });

            modelBuilder.Entity("Veiling.Server.Models.Bod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Betaald")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Datumtijd")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GebruikerId")
                        .HasColumnType("int");

                    b.Property<int>("HoeveelheidContainers")
                        .HasColumnType("int");

                    b.Property<int?>("KavelId")
                        .HasColumnType("int");

                    b.Property<float>("Koopprijs")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("GebruikerId");

                    b.HasIndex("KavelId");

                    b.ToTable("Boden");
                });

            modelBuilder.Entity("Veiling.Server.Models.Gebruiker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BedrijfId")
                        .HasColumnType("int");

                    b.Property<bool>("Bedrijfsbeheerder")
                        .HasColumnType("bit");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Geverifieerd")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PhoneNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BedrijfId");

                    b.ToTable("Gebruikers");
                });

            modelBuilder.Entity("Veiling.Server.Models.Kavel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Aantal")
                        .HasColumnType("int");

                    b.Property<string>("AfbeeldingUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Beschrijving")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fustcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kleur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kwaliteit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lengte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LeverancierId")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaatsVanVerkoop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stadium")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("StartPrijs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("VeilingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeverancierId");

                    b.HasIndex("VeilingId");

                    b.ToTable("Kavels");
                });

            modelBuilder.Entity("Veiling.Server.Models.Leverancier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BedrijfId")
                        .HasColumnType("int");

                    b.Property<string>("IndexOfReliabilityOfInformation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BedrijfId");

                    b.ToTable("Leveranciers");
                });

            modelBuilder.Entity("Veiling.Server.Models.Veiling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndTijd")
                        .HasColumnType("datetime2");

                    b.Property<float>("GeldPerTickCode")
                        .HasColumnType("real");

                    b.Property<int>("KlokId")
                        .HasColumnType("int");

                    b.Property<float>("Klokduur")
                        .HasColumnType("real");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTijd")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VeilingmeesterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VeilingmeesterId");

                    b.ToTable("Veilingen");
                });

            modelBuilder.Entity("Veiling.Server.Models.Veilingmeester", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AantalVeilingenBeheerd")
                        .HasColumnType("int");

                    b.Property<int>("GebruikerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GebruikerId");

                    b.ToTable("Veilingmeesters");
                });

            modelBuilder.Entity("Veiling.Server.Models.Bod", b =>
                {
                    b.HasOne("Veiling.Server.Models.Gebruiker", "Gebruiker")
                        .WithMany("Boden")
                        .HasForeignKey("GebruikerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Veiling.Server.Models.Kavel", "Kavel")
                        .WithMany("Boden")
                        .HasForeignKey("KavelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Gebruiker");

                    b.Navigation("Kavel");
                });

            modelBuilder.Entity("Veiling.Server.Models.Gebruiker", b =>
                {
                    b.HasOne("Veiling.Server.Models.Bedrijf", "Bedrijf")
                        .WithMany("Gebruikers")
                        .HasForeignKey("BedrijfId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Bedrijf");
                });

            modelBuilder.Entity("Veiling.Server.Models.Kavel", b =>
                {
                    b.HasOne("Veiling.Server.Models.Leverancier", "Leverancier")
                        .WithMany("Kavels")
                        .HasForeignKey("LeverancierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Veiling.Server.Models.Veiling", "Veiling")
                        .WithMany("Kavels")
                        .HasForeignKey("VeilingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Leverancier");

                    b.Navigation("Veiling");
                });

            modelBuilder.Entity("Veiling.Server.Models.Leverancier", b =>
                {
                    b.HasOne("Veiling.Server.Models.Bedrijf", "Bedrijf")
                        .WithMany()
                        .HasForeignKey("BedrijfId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Bedrijf");
                });

            modelBuilder.Entity("Veiling.Server.Models.Veiling", b =>
                {
                    b.HasOne("Veiling.Server.Models.Veilingmeester", "Veilingmeester")
                        .WithMany("Veilingen")
                        .HasForeignKey("VeilingmeesterId");

                    b.Navigation("Veilingmeester");
                });

            modelBuilder.Entity("Veiling.Server.Models.Veilingmeester", b =>
                {
                    b.HasOne("Veiling.Server.Models.Gebruiker", "Gebruiker")
                        .WithMany()
                        .HasForeignKey("GebruikerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gebruiker");
                });

            modelBuilder.Entity("Veiling.Server.Models.Bedrijf", b =>
                {
                    b.Navigation("Gebruikers");
                });

            modelBuilder.Entity("Veiling.Server.Models.Gebruiker", b =>
                {
                    b.Navigation("Boden");
                });

            modelBuilder.Entity("Veiling.Server.Models.Kavel", b =>
                {
                    b.Navigation("Boden");
                });

            modelBuilder.Entity("Veiling.Server.Models.Leverancier", b =>
                {
                    b.Navigation("Kavels");
                });

            modelBuilder.Entity("Veiling.Server.Models.Veiling", b =>
                {
                    b.Navigation("Kavels");
                });

            modelBuilder.Entity("Veiling.Server.Models.Veilingmeester", b =>
                {
                    b.Navigation("Veilingen");
                });
#pragma warning restore 612, 618
        }
    }
}
